require("sprite")

Sprites = {}
Sprites["chair"] = Sprite:new(Rectangle:new(0, 0, 9, 16), black)
Sprites["character"] = {}
Sprites["character"]["back"] = {}
Sprites["character"]["back"]["stand"] = {}
Sprites["character"]["back"]["stand"]["stand0"] = Sprite:new(Rectangle:new(9, 0, 5, 15), black)
Sprites["character"]["back"]["walk"] = {}
Sprites["character"]["back"]["walk"]["character_back_walk0"] = Sprite:new(Rectangle:new(14, 0, 5, 15), black)
Sprites["character"]["back"]["walk"]["character_back_walk1"] = Sprite:new(Rectangle:new(19, 0, 5, 15), black)
Sprites["character"]["back"]["walk"]["character_back_walk2"] = Sprite:new(Rectangle:new(24, 0, 5, 15), black)
Sprites["character"]["back"]["walk"]["character_back_walk3"] = Sprite:new(Rectangle:new(29, 0, 5, 15), black)
Sprites["character"]["back"]["walk"]["character_back_walk4"] = Sprite:new(Rectangle:new(34, 0, 5, 15), black)
Sprites["character"]["back"]["walk"]["character_back_walk5"] = Sprite:new(Rectangle:new(39, 0, 5, 15), black)
Sprites["character"]["front"] = {}
Sprites["character"]["front"]["stand"] = Sprite:new(Rectangle:new(44, 0, 5, 15), black)
Sprites["character"]["front"]["walk"] = {}
Sprites["character"]["front"]["walk"]["character_front_walk0"] = Sprite:new(Rectangle:new(49, 0, 5, 15), black)
Sprites["character"]["front"]["walk"]["character_front_walk1"] = Sprite:new(Rectangle:new(54, 0, 5, 15), black)
Sprites["character"]["front"]["walk"]["character_front_walk2"] = Sprite:new(Rectangle:new(59, 0, 5, 15), black)
Sprites["character"]["front"]["walk"]["character_front_walk3"] = Sprite:new(Rectangle:new(64, 0, 5, 15), black)
Sprites["character"]["front"]["walk"]["character_front_walk4"] = Sprite:new(Rectangle:new(69, 0, 5, 15), black)
Sprites["character"]["front"]["walk"]["character_front_walk5"] = Sprite:new(Rectangle:new(74, 0, 5, 15), black)
Sprites["character"]["side"] = {}
Sprites["character"]["side"]["stand"] = Sprite:new(Rectangle:new(79, 0, 5, 15), black)
Sprites["character"]["side"]["walk"] = {}
Sprites["character"]["side"]["walk"]["character_side_walk0"] = Sprite:new(Rectangle:new(84, 0, 5, 15), black)
Sprites["character"]["side"]["walk"]["character_side_walk1"] = Sprite:new(Rectangle:new(89, 0, 5, 15), black)
Sprites["character"]["side"]["walk"]["character_side_walk2"] = Sprite:new(Rectangle:new(94, 0, 5, 15), black)
Sprites["character"]["side"]["walk"]["character_side_walk3"] = Sprite:new(Rectangle:new(99, 0, 5, 15), black)
Sprites["character"]["side"]["walk"]["character_side_walk4"] = Sprite:new(Rectangle:new(104, 0, 5, 15), black)
Sprites["character"]["side"]["walk"]["character_side_walk5"] = Sprite:new(Rectangle:new(109, 0, 5, 15), black)
Sprites["cup"] = Sprite:new(Rectangle:new(0, 16, 16, 14), black)
Sprites["table"] = Sprite:new(Rectangle:new(16, 16, 20, 16), black)
